### ISSUE TITLE
Apply Options from csscss

### ISSUE THREAD

**Issue by rainbow-pooping-unicorn** [garthenweb/csscssbeauty#1]
Some further options doesn't run on csscssbeauty. 

I tried the following code: 
csscssbeauty -n 2 --no-match-shorthand .../...css 

but the option "--no-match-shorthand" does not work. Could you please apply this feature?
I think it's very useful.

Thank you

**Comment by garthenweb** [comment]
There were some issues with argument passing to the csscss process. This should be fixed with version 0.1.1.
